repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-merge-conflict
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint

-  repo: local
   hooks:
    -   id: gstreamer
        name: gstreamer
        entry: hooks/gstreamer.hook
        language: script
        files: ^gst.*\.(c|h|cpp)$
